# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-02 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enigma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_answer', models.CharField(max_length=200)),
                ('secret_key', models.CharField(max_length=200)),
                ('next_key', models.CharField(max_length=200)),
                ('template_name', models.CharField(max_length=200)),
            ],
        ),
    ]
